import $ivy.`org.xerial:sqlite-jdbc:3.18.0`
import $ivy.`org.tpolecat::doobie-core:0.5.2`
import $ivy.`org.tpolecat::doobie-postgres:0.5.2`
import $ivy.`org.tpolecat::doobie-hikari:0.5.2`
import $ivy.`com.chuusai::shapeless:2.3.3`
import $ivy.`io.circe::circe-core:0.9.3`
import $ivy.`io.circe::circe-generic:0.9.3`
import $ivy.`io.circe::circe-generic-extras:0.9.3`
import $ivy.`io.circe::circe-parser:0.9.3`